-- Supabase Dashboard > SQL Editor에서 실행합니다.
-- 이 스키마는 Supabase Auth 사용자와 Product RLS 권한을 함께 구성합니다.

-- 1. 애플리케이션에서 사용할 역할은 일반 사용자와 관리자 두 가지입니다.
DO $$
BEGIN
    CREATE TYPE public.app_role AS ENUM ('user', 'admin');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END
$$;

-- 2. auth.users의 공개 프로필만 별도 테이블에 저장합니다.
-- 비밀번호는 Supabase Auth가 관리하므로 이 테이블에는 저장하지 않습니다.
CREATE TABLE IF NOT EXISTS public.user_profiles (
    user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT NOT NULL,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 3. 사용자의 권한을 저장합니다. 신규 사용자의 기본 역할은 user입니다.
CREATE TABLE IF NOT EXISTS public.user_roles (
    user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    role public.app_role NOT NULL DEFAULT 'user'
);

-- 4. 실제 Product CRUD에 사용할 테이블입니다.
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    price INTEGER NOT NULL CHECK (price >= 0),
    created_by UUID REFERENCES auth.users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 5. Supabase Auth에 사용자가 생기면 프로필과 일반 사용자 역할을 자동 생성합니다.
CREATE OR REPLACE FUNCTION public.handle_new_auth_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
    INSERT INTO public.user_profiles (user_id, email, name)
    VALUES (
        NEW.id,
        COALESCE(NEW.email, ''),
        COALESCE(NEW.raw_user_meta_data ->> 'name', '')
    )
    ON CONFLICT (user_id) DO NOTHING;

    INSERT INTO public.user_roles (user_id, role)
    VALUES (NEW.id, 'user')
    ON CONFLICT (user_id) DO NOTHING;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
AFTER INSERT ON auth.users
FOR EACH ROW EXECUTE FUNCTION public.handle_new_auth_user();

-- 이미 가입되어 있던 Auth 사용자에게도 프로필과 기본 역할을 만들어 줍니다.
INSERT INTO public.user_profiles (user_id, email, name)
SELECT
    id,
    COALESCE(email, ''),
    COALESCE(raw_user_meta_data ->> 'name', '')
FROM auth.users
ON CONFLICT (user_id) DO NOTHING;

INSERT INTO public.user_roles (user_id, role)
SELECT id, 'user'
FROM auth.users
ON CONFLICT (user_id) DO NOTHING;

-- 6. RLS 정책에서 반복해서 사용할 관리자 확인 함수입니다.
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
    SELECT EXISTS (
        SELECT 1
        FROM public.user_roles
        WHERE user_id = auth.uid()
          AND role = 'admin'
    );
$$;

-- 7. 세 테이블 모두 RLS를 활성화합니다.
ALTER TABLE public.user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- SQL을 여러 번 실행해도 정책 이름이 충돌하지 않도록 기존 정책을 먼저 삭제합니다.
DROP POLICY IF EXISTS "사용자는 자신의 프로필 조회 가능" ON public.user_profiles;
DROP POLICY IF EXISTS "사용자는 자신의 역할 조회 가능" ON public.user_roles;
DROP POLICY IF EXISTS "로그인 사용자는 상품 조회 가능" ON public.products;
DROP POLICY IF EXISTS "관리자만 상품 생성 가능" ON public.products;
DROP POLICY IF EXISTS "관리자만 상품 수정 가능" ON public.products;
DROP POLICY IF EXISTS "관리자만 상품 삭제 가능" ON public.products;

-- 로그인 사용자는 자신의 프로필과 역할만 읽을 수 있습니다.
CREATE POLICY "사용자는 자신의 프로필 조회 가능"
ON public.user_profiles FOR SELECT TO authenticated
USING ((SELECT auth.uid()) = user_id);

CREATE POLICY "사용자는 자신의 역할 조회 가능"
ON public.user_roles FOR SELECT TO authenticated
USING ((SELECT auth.uid()) = user_id);

-- 일반 사용자와 관리자는 모두 상품을 조회할 수 있습니다.
CREATE POLICY "로그인 사용자는 상품 조회 가능"
ON public.products FOR SELECT TO authenticated
USING (true);

-- Product 생성·수정·삭제는 관리자 역할만 통과합니다.
CREATE POLICY "관리자만 상품 생성 가능"
ON public.products FOR INSERT TO authenticated
WITH CHECK ((SELECT public.is_admin()));

CREATE POLICY "관리자만 상품 수정 가능"
ON public.products FOR UPDATE TO authenticated
USING ((SELECT public.is_admin()))
WITH CHECK ((SELECT public.is_admin()));

CREATE POLICY "관리자만 상품 삭제 가능"
ON public.products FOR DELETE TO authenticated
USING ((SELECT public.is_admin()));

-- Data API의 authenticated 역할에 테이블 명령 권한을 주고,
-- 실제 허용 여부는 위의 RLS 정책이 최종 판단합니다.
GRANT SELECT ON public.user_profiles TO authenticated;
GRANT SELECT ON public.user_roles TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.products TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.products_id_seq TO authenticated;

-- 최초 관리자 지정 예시:
-- UPDATE public.user_roles
-- SET role = 'admin'
-- WHERE user_id = 'Supabase Authentication > Users에서 확인한 UUID';
